defaults:
 - perturbator: dev
 - wandb: default
 - activation_writer: dev
 - activation_reader: dev
 - dataset: libero
 - model: dev
 - method: dev

stage: dev
seed: 42
device: cuda
mode: evaluate
hydra:
  output_subdir: null
