#!/bin/bash --login
#SBATCH -p gpuA
#SBATCH -G 1
#SBATCH -c 8
#SBATCH -t 4-0
#SBATCH --mail-type=ALL
#SBATCH --mail-user=theodor.wulff@manchester.ac.uk
#SBATCH --array=0-4

echo "Job is using $SLURM_GPUS GPU(s) with ID(s) $CUDA_VISIBLE_DEVICES and $SLURM_NTASKS CPU core(s)"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK # reduce overloading GPU node
export HF_HOME="$PWD/.hfcache"

module purge
module load libs/cuda

# Print job information
echo "Job started at: $(date)"
echo "Running on node: $(hostname)"
echo "Job ID: $SLURM_JOB_ID"


# semantic_scale and synonym each run for noun and verb.
PERTURBATIONS=(
    "directional"
    "semantic_scale"
    "semantic_scale"
    "synonym"
    "synonym"
)
TARGET_WORDS=(
    "noun"    # ignored for directional, but keep array lengths aligned
    "noun"
    "verb"
    "noun"
    "verb"
)

INDEX=${SLURM_ARRAY_TASK_ID}
PERTURBATOR=${PERTURBATIONS[$INDEX]}
TARGET_WORD=${TARGET_WORDS[$INDEX]}

echo "Evaluation with perturbator=${PERTURBATOR} and target_word=${TARGET_WORD}"

source "$PWD/.venv/bin/activate"

if [ "$PERTURBATOR" == "directional" ]; then
    python main.py --config-name=activation_patching perturbator=${PERTURBATOR}
else
    python main.py --config-name=activation_patching perturbator=${PERTURBATOR} perturbator.target_words="${TARGET_WORD}"
fi

deactivate

# Print completion message
echo "Job finished at: $(date)"
