#!/bin/bash --login
#SBATCH -p gpuA
#SBATCH -G 1
#SBATCH -c 8
#SBATCH -t 4-0
#SBATCH --mail-type=ALL
#SBATCH --mail-user=theodor.wulff@manchester.ac.uk
#SBATCH --array=0-1

echo "Job is using $SLURM_GPUS GPU(s) with ID(s) $CUDA_VISIBLE_DEVICES and $SLURM_NTASKS CPU core(s)"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK # reduce overloading GPU node
export HF_HOME="$PWD/.hfcache"

module purge
module load libs/cuda

# Print job information
echo "Job started at: $(date)"
echo "Running on node: $(hostname)"
echo "Job ID: $SLURM_JOB_ID"


# semantic_scale and synonym each run for noun and verb.
CONFIGS=(
    "full_ood_object"
    "full_empty"
    "groot_ood_object"
    "groot_empty"
)

INDEX=${SLURM_ARRAY_TASK_ID}
CONFIG=${CONFIGS[$INDEX]}

echo "Running attribution patching with config=${CONFIG}"

source "$PWD/.venv/bin/activate"

python main.py --config-name=${CONFIG}

deactivate

# Print completion message
echo "Job finished at: $(date)"
